# Generated by Django 4.0 on 2021-12-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Positon',
            new_name='Position',
        ),
    ]
